<?php

function anaheimoc_blocks_block($op = 'list', $delta = 0, $edit = array()) {
if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Quick RFP Block'), 
    );

    $blocks[1] = array(
      'info' => t('Request Partner Information Block'),
    );
    
    $blocks[2] = array(
      'info' => t('Visitors Newsletter Signup'),
    );
    
    $blocks[3] = array(
      'info' => t('Meetings Newsletter Signup'),
    );
    
    $blocks[4] = array(
      'info' => t('Travel Trade Newsletter Signup'),
    );
    
    $blocks[5] = array(
      'info' => t('Press Newsletter Signup'),
    );
    
    $blocks[6] = array(
      'info' => t('Hotels Within ACC Walking Distance'),
    );

    return $blocks;
  }
  
  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Quick RFP'), 
          'content' => '<p>Ready to start planning your meeting or convention in Anahiem/Orange County? Your successful meeting awaits.</p><div id="call_to_action"><a class="button" href="/meetings/contact/quick-rfp">SUBMIT A QUICK RFP!</a></div>',
        );
        break;
      case 1:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Become a Partner'), 
          'content' => '<p>Interested in becoming a partner of the Anaheim/Orange County Visitor &amp; Convention Bureau?</p><div id="call_to_action"><a href="/become-a-partner/request-info" class="button">REQUEST PARTNERSHIP INFO!</a></div>',
        );
        break;
        case 2:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Visitors Newsletter Signup'), 
          'content' => '',
        );
        break;
        case 3:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Meetings Newsletter Signup'), 
          'content' => '',
        );
        break;
        case 4:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Travel Trade Newsletter Signup'), 
          'content' => '',
        );
        break;
        case 5:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Press Newsletter Signup'), 
          'content' => '',
        );
        break;
        case 6:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Hotel Map - Walking Distance Hotels'), 
          'content' => '<img src="/sites/default/files/assets/misc/walkingdistance6.GIF" />
          <ol>
           <li>Disneyland Hotel - 990 Rooms</li>
           <li>Disney\'s Grand Californian Hotel - 745 rooms</li>
           <li>Disney\'s Paradise Pier Hotel - 489 rooms</li>
           <li>Hilton Anaheim - 1,572 rooms</li>
           <li>Anaheim Marriott - 1,031 rooms</li>
           <li>Sheraton Park Hotel - 490 rooms</li>
           <li>Hyatt Regency Orange County - 654 rooms</li>
           <li>Best Western Stovall\'s Inn - 289 rooms</li>
           <li>Anabella Hotel - 336 rooms</li>
           <li>Residence Inn by Marriott Anaheim Maingate - 200 rooms</li>
           <li>Castle Inn and Suites - 249 rooms</li>
           <li>Motel 6 Anaheim Maingate - 230 rooms</li>
           <li>Clarion Hotel Anaheim Resort - 284 rooms</li>
           <li>Red Lion Hotel Anaheim - 314 rooms</li>
           <li>Doubletree Guest Suites Convention Center - 252 rooms</li>
           <li>Embassy Suites Hotel Anaheim South - 375 rooms</li>
           <li>Residence Inn Anaheim Resort Area - 200 rooms</li>
          </ol> ',
        );
        break;
    }
    return $block;
  }
}