<?php

function anaheimoc_blocks_block($op = 'list', $delta = 0, $edit = array()) {
if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Quick RFP Block'), 
    );

    $blocks[1] = array(
      'info' => t('Request Partner Information Block'),
    );

    return $blocks;
  }
  
  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Quick RFP'), 
          'content' => '<p>Ready to start planning your meeting or convention in Anahiem/Orange County? Your successful meeting awaits.</p><div id="call_to_action"><a class="button" href="/meetings/contact/quick-rfp">SUBMIT A QUICK RFP!</a></div>',
        );
        break;
      case 1:
        // Your module will need to define this function to render the block.
        $block = array(
          'subject' => t('Become a Partner'), 
          'content' => '<p>Interested in becoming a partner of the Anaheim/Orange County Visitor &amp; Convention Bureau?</p><div id="call_to_action"><a href="/become-a-partner/request-info" class="button">REQUEST PARTNERSHIP INFO!</a></div>',
        );
        break;
    }
    return $block;
  }
}