<?php

/**
 * Implementation of hook_content_default_fields().
 */
function anaheimoc_page_content_default_fields() {
  $fields = array();

  // Exported field: field_anaheimoc_page_hero_image
  $fields['anaheimoc_page-field_anaheimoc_page_hero_image'] = array(
    'field_name' => 'field_anaheimoc_page_hero_image',
    'type_name' => 'anaheimoc_page',
    'display_settings' => array(
      'weight' => '1',
      'parent' => 'group_hero_feature_options',
      'label' => array(
        'format' => 'hidden',
      ),
      'teaser' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      'full' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      '4' => array(
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'image_plain',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'filefield',
    'required' => '0',
    'multiple' => '0',
    'module' => 'filefield',
    'active' => '1',
    'list_field' => '0',
    'list_default' => 1,
    'description_field' => '1',
    'widget' => array(
      'file_extensions' => 'png gif jpg jpeg',
      'file_path' => '',
      'progress_indicator' => 'bar',
      'max_filesize_per_file' => '',
      'max_filesize_per_node' => '',
      'max_resolution' => '940x290',
      'min_resolution' => '940x290',
      'alt' => '',
      'custom_alt' => 1,
      'title' => '',
      'custom_title' => 1,
      'title_type' => 'textfield',
      'default_image' => NULL,
      'use_default_image' => 0,
      'filefield_sources' => array(
        'remote' => 0,
        'reference' => 0,
        'attach' => 0,
      ),
      'filefield_source_attach_path' => 'file_attach',
      'filefield_source_attach_absolute' => '0',
      'filefield_source_attach_mode' => 'move',
      'filefield_source_autocomplete' => '0',
      'label' => 'Hero feature image',
      'weight' => '1',
      'description' => 'Upload an image to use in the home page slideshow (if applicable).  Image must be 940x290 pixels.',
      'type' => 'imagefield_widget',
      'module' => 'imagefield',
    ),
  );

  // Exported field: field_anaheimoc_page_hero_tax
  $fields['anaheimoc_page-field_anaheimoc_page_hero_tax'] = array(
    'field_name' => 'field_anaheimoc_page_hero_tax',
    'type_name' => 'anaheimoc_page',
    'display_settings' => array(
      'weight' => 0,
      'parent' => 'group_hero_feature_options',
      'label' => array(
        'format' => 'hidden',
      ),
      'teaser' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      'full' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'content_taxonomy',
    'required' => '0',
    'multiple' => '0',
    'module' => 'content_taxonomy',
    'active' => '1',
    'save_term_node' => 0,
    'vid' => '25',
    'parent' => '0',
    'parent_php_code' => '',
    'depth' => '',
    'widget' => array(
      'group_parent' => '0',
      'show_depth' => 1,
      'default_value' => NULL,
      'default_value_php' => NULL,
      'label' => 'Hero feature',
      'weight' => 0,
      'description' => '',
      'type' => 'content_taxonomy_options',
      'module' => 'content_taxonomy_options',
    ),
  );

  // Exported field: field_anaheimoc_page_hero_weight
  $fields['anaheimoc_page-field_anaheimoc_page_hero_weight'] = array(
    'field_name' => 'field_anaheimoc_page_hero_weight',
    'type_name' => 'anaheimoc_page',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'number_integer',
    'required' => '0',
    'multiple' => '0',
    'module' => 'number',
    'active' => '1',
    'prefix' => '',
    'suffix' => '',
    'min' => '',
    'max' => '',
    'allowed_values' => '-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
0
1
2
3
4
5
6
7
8
9
10',
    'allowed_values_php' => '',
    'widget' => array(
      'default_value' => NULL,
      'default_value_php' => NULL,
      'label' => 'Hero feature image weight',
      'weight' => '2',
      'description' => '',
      'type' => 'optionwidgets_select',
      'module' => 'optionwidgets',
    ),
  );

  // Exported field: field_anaheimoc_page_reference
  $fields['anaheimoc_page-field_anaheimoc_page_reference'] = array(
    'field_name' => 'field_anaheimoc_page_reference',
    'type_name' => 'anaheimoc_page',
    'display_settings' => array(
      'weight' => '12',
      'parent' => '',
      'label' => array(
        'format' => 'hidden',
      ),
      'teaser' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      'full' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'nodereference',
    'required' => '0',
    'multiple' => '0',
    'module' => 'nodereference',
    'active' => '1',
    'referenceable_types' => array(
      'anaheimoc_page' => 'anaheimoc_page',
      'ad' => 0,
      'partner_listing_associate' => 0,
      'basic_profile' => 0,
      'blog_article' => 0,
      'blogger_profile' => 0,
      'convention_calendar' => 0,
      'coupon' => 0,
      'event_leisure' => 0,
      'feed_fast' => 0,
      'gallery' => 0,
      'front_slideshow' => 0,
      'gallery_image' => 0,
      'image_library_img' => 0,
      'job_posting' => 0,
      'media_contact' => 0,
      'media_outlet' => 0,
      'matching' => 0,
      'media_clipping' => 0,
      'venue_rooms' => 0,
      'microsite' => 0,
      'page' => 0,
      'multichoice' => 0,
      'oc_specialist_updates' => 0,
      'partner_event' => 0,
      'partner_listing' => 0,
      'partner_discounts' => 0,
      'partner_spotlight' => 0,
      'podcast' => 0,
      'press_release' => 0,
      'profile' => 0,
      'pr_contact' => 0,
      'quiz' => 0,
      'quiz_directions' => 0,
      'sybas_offer' => 0,
      'sybas_page' => 0,
      'staff_profile' => 0,
      'story' => 0,
      'testimonial' => 0,
      'travel_trade_pro_discounts' => 0,
      'travel_trade_opp' => 0,
      'truefalse' => 0,
      'webform' => 0,
      'whats_new_article' => 0,
    ),
    'advanced_view' => '--',
    'advanced_view_args' => '',
    'widget' => array(
      'node_link' => array(
        'teaser' => 0,
        'full' => 1,
        'title' => 'Attach Content To This Page',
        'hover_title' => '',
        'destination' => 'node',
      ),
      'fallback' => 'autocomplete',
      'edit_fallback' => 1,
      'label' => 'Page reference',
      'weight' => '10',
      'description' => '',
      'type' => 'nodereference_url',
      'module' => 'nodereference_url',
    ),
  );

  // Exported field: field_anaheimoc_page_weight
  $fields['anaheimoc_page-field_anaheimoc_page_weight'] = array(
    'field_name' => 'field_anaheimoc_page_weight',
    'type_name' => 'anaheimoc_page',
    'display_settings' => array(
      'weight' => '3',
      'parent' => '',
      'label' => array(
        'format' => 'hidden',
      ),
      'teaser' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      'full' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'number_integer',
    'required' => '0',
    'multiple' => '0',
    'module' => 'number',
    'active' => '1',
    'prefix' => '',
    'suffix' => '',
    'min' => '',
    'max' => '',
    'allowed_values' => '-10
-9
-8
-7
-6
-5
-4
-3
-2
-1
0
1
2
3
4
5
6
7
8
9
10',
    'allowed_values_php' => '',
    'widget' => array(
      'default_value' => NULL,
      'default_value_php' => NULL,
      'label' => 'Page weight',
      'weight' => '-1',
      'description' => 'Use this field to order children pages when attached to their parent page.',
      'type' => 'optionwidgets_select',
      'module' => 'optionwidgets',
    ),
  );

  // Exported field: field_article_image
  $fields['anaheimoc_page-field_article_image'] = array(
    'field_name' => 'field_article_image',
    'type_name' => 'anaheimoc_page',
    'display_settings' => array(
      'weight' => '-2',
      'parent' => '',
      'label' => array(
        'format' => 'hidden',
      ),
      'teaser' => array(
        'format' => 'hidden',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'page_main_image_default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'image_plain',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'image_plain',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'filefield',
    'required' => '0',
    'multiple' => '0',
    'module' => 'filefield',
    'active' => '1',
    'list_field' => '0',
    'list_default' => 1,
    'description_field' => '1',
    'widget' => array(
      'file_extensions' => 'png gif jpg jpeg',
      'file_path' => 'assets/anaheimoc_page/images',
      'progress_indicator' => 'bar',
      'max_filesize_per_file' => '',
      'max_filesize_per_node' => '',
      'max_resolution' => '1240x920',
      'min_resolution' => '620x460',
      'alt' => '',
      'custom_alt' => 1,
      'title' => '',
      'custom_title' => 1,
      'title_type' => 'textfield',
      'default_image' => NULL,
      'use_default_image' => 0,
      'filefield_sources' => array(
        'remote' => 'remote',
        'reference' => 0,
        'attach' => 0,
      ),
      'filefield_source_attach_path' => 'file_attach',
      'filefield_source_attach_absolute' => '0',
      'filefield_source_attach_mode' => 'move',
      'filefield_source_autocomplete' => '0',
      'label' => 'Main image',
      'weight' => '-4',
      'description' => '',
      'type' => 'imagefield_widget',
      'module' => 'imagefield',
    ),
  );

  // Exported field: field_partner_list_builder
  $fields['anaheimoc_page-field_partner_list_builder'] = array(
    'field_name' => 'field_partner_list_builder',
    'type_name' => 'anaheimoc_page',
    'display_settings' => array(
      'weight' => '11',
      'parent' => '',
      'label' => array(
        'format' => 'hidden',
      ),
      'teaser' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      'full' => array(
        'format' => 'hidden',
        'exclude' => 1,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'text',
    'required' => '0',
    'multiple' => '0',
    'module' => 'text',
    'active' => '1',
    'text_processing' => '0',
    'max_length' => '',
    'allowed_values' => '',
    'allowed_values_php' => '',
    'widget' => array(
      'rows' => 5,
      'size' => '60',
      'semantic_cck_widget_settings' => array(
        'use_widget_settings' => 0,
      ),
      'default_value' => array(
        '0' => array(
          'value' => '',
          '_error_element' => 'default_value_widget][field_partner_list_builder][0][value',
        ),
      ),
      'default_value_php' => NULL,
      'label' => 'Partner category/city',
      'weight' => '9',
      'description' => 'This field accepts two arguments separated by a /.  The first argument is the category ID.  This argument supports multiple category IDs (ex: 6450+6521+6520).  The second argument (optional) accepts the name of a city.  This argument filters category results by city.  Here are a couple of examples of a full entry: 6520/buena-park - OR - 6520 - OR - 6520+6521/fullerton.',
      'type' => 'text_textfield',
      'module' => 'text',
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Hero feature');
  t('Hero feature image');
  t('Hero feature image weight');
  t('Main image');
  t('Page reference');
  t('Page weight');
  t('Partner category/city');

  return $fields;
}
