<?php
// $Id: webform_rules.module,v 1.1.2.9 2010/12/18 16:16:34 stborchert Exp $

/**
 * @file
 * Adds rules integration for webform submissions.
 */

/**
 * Implementation of hook_form_alter().
 */
function webform_rules_form_alter(&$form, $form_state, $form_id) {
  if (strpos($form_id, 'webform_client_form_') !== FALSE) {
    // Add custom submit handler to webform form.
    $form['#submit'][] = 'webform_rules_client_form_submit';
  }
}

/**
 * Custom submit handler for webform submissions.
 */
function webform_rules_client_form_submit($form, &$form_state) {
  $values = $form_state['values'];
  // Check if user is submitting as a draft.
  $is_draft = $values['op'] == t('Save Draft');
  // Get webform node.
  $node = $form['#node'];
  // Save submission id.
  $node->webform['sid'] = $is_draft ? '' : $values['details']['sid'];
  // Get submitted data from webform.
  $submission_data = webform_submission_data($node, $values['submitted']);
  // Invoke event.
  webform_rules_rules_invoke_event($submission_data, $node, $is_draft);
}

/**
 * Invoke rules event with submitted data.
 *
 * @param $submission_data
 *   Data from webform prepared by webform_submission_data().
 * @param $webform
 *   The submitted webform.
 * @param $is_draft
 *   TRUE if the webform is saved as draft, otherwise FALSE. Defaults to FALSE.
 */
function webform_rules_rules_invoke_event($submission_data, $node, $is_draft = FALSE) {
  global $user;
  if (!is_array($submission_data) || count($submission_data) == 0) {
    return;
  }
  $webform = $node->webform;
  $data = array(
    'sid' => $webform['sid'],
    'components' => array(),
  );
  $form_id = 'webform-client-form-'. $webform['nid'];
  // Map values to field names.
  foreach ($submission_data as $cid => $value) {
    $component = $webform['components'][$cid];
    $data['components'][$component['form_key']]['value'] = $value['value'];
    $data['components'][$component['form_key']]['component'] = $component;
  }
  // Invoke the rules event.
  if ($is_draft) {
    rules_invoke_event('webform_rules_submit_as_draft', array(
      'user' => $user,
      'node' => $node,
      'data' => $data,
      'form_id' => $form_id,
    ));
  }
  else {
    rules_invoke_event('webform_rules_submit', array(
      'user' => $user,
      'node' => $node,
      'data' => $data,
      'form_id' => $form_id,
    ));
  }
}

/**
 * Implementation of hook_token_list().
 */
function webform_rules_token_list($type) {
  if ($type == 'webform' || $type == 'all') {
    $list['webform']['sid'] = t('The submission id.');
    $list['webform']['data'] = t('The submitted webform data.');
    $list['webform']['data-raw'] = t('The unfiltered submitted webform data.');
    $list['webform']['{component}-title'] = t('The title of the selected component, e.g. "email-title".');
    $list['webform']['{component}-value'] = t('The value of the selected component, e.g. "email-value".');
    $list['webform']['{component}-value-html'] = t('The value of the selected component rendered as html, e.g. "email-value-html".');
    $list['webform']['{component}-value-raw'] = t('The unfiltered value of the selected component, e.g. "email-value-raw".');
    $list['webform']['{component}-display'] = t('Title and value of the selected component, e.g. "email-display".');
    $list['webform']['{component}-display-html'] = t('Title and value of the selected component rendered as html, e.g. "email-display-html".');
    return $list;
  }
}

/**
 * Implementation of hook_token_values().
 */
function webform_rules_token_values($type, $object = NULL, $options = array()) {
  $values = array();
  if (!is_array($object) || !is_array($object['components'])) {
    return $values;
  }
  switch ($type) {
    case 'webform':
      // Get webform data as token values.
      $values['sid'] = $object['sid'];
      $values['data'] = webform_rules_prepare_component_value($object);
      $values['data-raw'] = webform_rules_prepare_component_value($object, TRUE);
      // Process components.
      $components = array_keys($object['components']);
      foreach ($components as $key) {
        $component = $object['components'][$key]['component'];
        $component_value = $object['components'][$key]['value'];
        // Get component title as token value.
        $values[$key .'-title'] = $component['name'];

        // Get value as token and render as text.
        // Full display (title: value).
        $values[$key .'-display'] = webform_rules_render_component($component, $component_value);
        // Get component value as token value.
        $values[$key .'-value'] = webform_rules_render_component($component, $component_value, 'text', FALSE);

        // Get value as token and render as html.
        // Full display (title: value).
        $values[$key .'-display-html'] = webform_rules_render_component($component, $component_value, 'html');
        // Get component value as token value.
        $values[$key .'-value-html'] = webform_rules_render_component($component, $component_value, 'html', FALSE);

        // Raw value.
        $values[$key .'-value-raw'] = webform_rules_prepare_component_value($component_value, TRUE);
      }
      break;
  }
  return $values;
}

/**
 * Prepare component value for output.
 * Code adapted from drupal_to_js().
 *
 * @param $component_value
 *   Value of submitted component.
 * @param $raw
 *   If TRUE, leave all values unfiltered.
 */
function webform_rules_prepare_component_value($component_value, $raw = FALSE) {
  switch (gettype($component_value)) {
    case 'boolean':
      return $component_value ? 'true' : 'false'; // Lowercase necessary!
    case 'integer':
    case 'double':
      return $var;
    case 'resource':
    case 'string':
      return $raw ? $component_value : check_plain($component_value);
    case 'array':
      // If the array is empty or if it has sequential whole number keys
      // starting with 0, it's not associative so we can go ahead and
      // convert it as an array.
      if (empty($component_value) || array_keys($component_value) === range(0, sizeof($component_value) - 1)) {
        $output = array();
        foreach ($component_value as $v) {
          $output[] = webform_rules_prepare_component_value($v, $raw);
        }
        return implode(', ', $output);
      }
      // Otherwise, fall through to convert the array as an object.
      // This is usefull for more readable output.
    case 'object':
      $output = array();
      foreach ($component_value as $k => $v) {
        $output[] = webform_rules_prepare_component_value(strval($k), $raw) . ': ' . webform_rules_prepare_component_value($v, $raw);
      }
      return implode(', ', $output);
    default:
      return 'null';
  }
}

/**
 * Render value of component.
 *
 * @param $component
 *   Webform component to render.
 * @param $value
 *   Submitted value of webform component.
 * @param $format
 *   How to render the components value ('html' or 'text'). Defaults to 'text'.
 * @param $title
 *   Renders the component title if set to TRUE.
 *
 * @return
 *   The rendered component value.
 */
function webform_rules_render_component($component, $value, $format = 'text', $title = TRUE) {
  if ($format != 'text') {
    $format = 'html';
  }
  $display_element = webform_component_invoke($component['type'], 'display', $component, $value, $format);
  $display_element['#parents'] = array('submitted', $component['form_key']);
  if (!isset($display_element['#id'])) {
    $display_element['#id'] = form_clean_id('edit-' . implode('-', $display_element['#parents']));
  }
  if (!$title) {
  	$display_element['#title'] = NULL;
  }
  return drupal_render($display_element);
}
