<?php
// $Id$

/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_form_alter().
 */
function image_library_register_terms_form_user_register_alter(&$form, $form_state) {	
	$form['image_library_register_terms_terms'] = array(
		'#type' => 'item',
		'#title' => t('Image Library Terms of Use'),
		'#value' => t('THE BIG BRAIN AM WINNING AGAIN! I AM THE GREETEST! NOW I AM LEAVING EARTH, FOR NO RAISEN!'),
	);
	$form['image_library_register_terms_checkbox'] = array(
		'#type' => 'checkbox',
		'#title' => t('I agree to the Image Library Terms of Use'),
		'#required' => TRUE,
	);
}

